"""empty message

Revision ID: c8d2e5324c57
Revises: bd3a03eeff51
Create Date: 2025-05-16 12:14:14.795015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d2e5324c57'
down_revision = 'bd3a03eeff51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('content')

    with op.batch_alter_table('detected', schema=None) as batch_op:
        batch_op.drop_column('total_count')
        batch_op.drop_column('match_count')

    # ### end Alembic commands ###
